import { CONFIG, DEFAULTS } from './config.js';
import { calculateNutrition, calibrateTdee, mealDistribution } from './calculator.js';
import { loadData, saveData, clearData } from './storage.js';

const form=document.querySelector('#calculator'),resultEl=document.querySelector('#result'),errorsEl=document.querySelector('#errors');
const installBtn=document.querySelector('#installBtn'),installHelp=document.querySelector('#installHelp'),platformBanner=document.querySelector('#platformBanner');
let step=1,lastResult=null,deferredPrompt=null,submitting=false,controllerReloaded=false;
const fields=['age','sex','height','weight','activity','goal','bodyFat','targetWeight','strength','cardio','duration','steps','workType','goalRate','pregnant','breastfeeding','kidney','liver','diabetes','eatingDisorder','medicalGuidance'];

function values(){const fd=new FormData(form),o={};for(let i=0;i<fields.length;i+=1){const k=fields[i],el=form.elements[k],value=fd.get(k);o[k]=el&&el.type==='checkbox'?el.checked:(value===null?'':value)}return o}
function setValues(data){const merged=Object.assign({},DEFAULTS,data||{}),keys=Object.keys(merged);for(let i=0;i<keys.length;i+=1){const k=keys[i],v=merged[k],el=form.elements[k];if(!el)continue;if(typeof RadioNodeList!=='undefined'&&el instanceof RadioNodeList){for(let j=0;j<el.length;j+=1){if(el[j].value===String(v)){el[j].checked=true;break}}}else if(el.type==='checkbox')el.checked=Boolean(v);else el.value=v}syncOutputs()}
function syncOutputs(){document.querySelector('#heightOut').value=form.height.value;document.querySelector('#weightOut').value=form.weight.value}
function safeScroll(el){try{el.scrollIntoView({behavior:'smooth',block:'center'})}catch(error){el.scrollIntoView()}}
function safeScrollTop(){try{window.scrollTo({top:0,behavior:'smooth'})}catch(error){window.scrollTo(0,0)}}
function save(){if(!saveData({profile:values()}))document.querySelector('#storageWarning').hidden=false}
function renderActivities(){document.querySelector('#activityChoices').innerHTML=Object.keys(CONFIG.activity).map(function(id){const a=CONFIG.activity[id];return `<label><input type="radio" name="activity" value="${id}"><span><b>${a.title}</b><small>${a.example}</small></span></label>`}).join('')}
function updateSteps(){document.querySelectorAll('.step').forEach(function(s){s.hidden=document.body.classList.contains('all-mode')?false:Number(s.dataset.step)!==step});document.querySelector('#prev').hidden=step===1||document.body.classList.contains('all-mode');document.querySelector('#next').hidden=step===5||document.body.classList.contains('all-mode');document.querySelector('#submit').hidden=step!==5&&!document.body.classList.contains('all-mode');safeScrollTop()}
function showErrors(errors){errorsEl.innerHTML='<b>⚠️ 请修改以下内容：</b><ul>'+errors.map(function(x){return `<li>${x}</li>`}).join('')+'</ul><p>特殊情况请咨询医生或营养师。</p>';errorsEl.hidden=false;safeScroll(errorsEl)}
const round=function(n){return Math.round(n)},pct=function(n){return Math.round(n*100)};
function renderResult(r){lastResult=r;const m=r.macros;resultEl.innerHTML=`<div class="hero">您每天大约可以吃：<strong>${round(r.target)} 千卡</strong></div>${r.warnings.map(function(w){return `<p class="warning">${w}</p>`}).join('')}<div class="macro-grid"><div class="macro">蛋白质<strong>${round(m.protein.grams)}克</strong><small>${round(m.protein.calories)}千卡 · ${pct(m.protein.share)}%</small></div><div class="macro">脂肪<strong>${round(m.fat.grams)}克</strong><small>${round(m.fat.calories)}千卡 · ${pct(m.fat.share)}%</small></div><div class="macro">碳水化合物<strong>${round(m.carbs.grams)}克</strong><small>${round(m.carbs.calories)}千卡 · ${pct(m.carbs.share)}%</small></div></div><div class="bar" aria-label="营养素热量比例"><span class="protein" style="width:${pct(m.protein.share)}%"></span><span class="fat" style="width:${pct(m.fat.share)}%"></span><span class="carbs" style="width:${pct(m.carbs.share)}%"></span></div><ul class="details-list"><li>基础代谢（BMR）：${round(r.bmr)} 千卡</li><li>维持体重所需热量（TDEE）：${round(r.tdee)} 千卡</li><li>维持热量参考范围：${round(r.tdeeRange[0])}～${round(r.tdeeRange[1])} 千卡</li><li>当前目标热量：${round(r.target)} 千卡</li><li>采用公式：${r.formula}</li><li>活动系数：${r.factor}</li><li>蛋白质计算依据：${r.referenceWeight.label} ${round(r.referenceWeight.value)} kg（${r.proteinRule.label}，${r.proteinRule.def}g/kg）</li></ul><p class="notice">实际维持热量会受到步数、训练强度、睡眠、肌肉量和个体差异影响，建议结合2至3周体重变化进行调整。</p><h3>分餐建议</h3><div class="mode"><button id="threeMeals" class="active" type="button">分成三餐</button><button id="fourMeals" type="button">分成四餐</button></div><div id="meals"></div>`;resultEl.hidden=false;renderMeals(3);resultEl.querySelector('#threeMeals').onclick=function(){renderMeals(3)};resultEl.querySelector('#fourMeals').onclick=function(){renderMeals(4)};safeScroll(resultEl)}
function renderMeals(count){const items=mealDistribution(lastResult,count);document.querySelector('#meals').innerHTML=items.map(function(x){return `<div class="meal"><b>${x.name} ${pct(x.ratio)}%</b>：约 ${round(x.calories)}千卡；蛋白质${round(x.protein)}克、脂肪${round(x.fat)}克、碳水${round(x.carbs)}克</div>`}).join('');document.querySelector('#threeMeals').classList.toggle('active',count===3);document.querySelector('#fourMeals').classList.toggle('active',count===4)}

function setupPlatformHelp(){const ua=navigator.userAgent||'',isWechat=/MicroMessenger/i.test(ua),isIOS=/iPad|iPhone|iPod/i.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);document.documentElement.classList.toggle('is-ios',isIOS);document.documentElement.classList.toggle('is-wechat',isWechat);installBtn.hidden=true;if(isWechat){platformBanner.hidden=false;platformBanner.textContent='微信中可以继续计算。如需添加到桌面，请点击右上角，选择在Safari中打开。';installHelp.innerHTML='<ol><li>点击微信右上角菜单</li><li>选择“在Safari中打开”</li><li>在Safari点分享，再选“添加到主屏幕”</li></ol>'}else if(isIOS){installHelp.innerHTML='<ol><li>使用Safari打开本页</li><li>点击底部分享按钮</li><li>选择“添加到主屏幕”</li></ol>'}else{installHelp.innerHTML='<ol><li>点击“添加到手机桌面”或浏览器菜单</li><li>选择“添加到主屏幕”</li><li>确认添加</li></ol>';window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferredPrompt=e;installBtn.hidden=false})}}
function setupServiceWorker(){if(!('serviceWorker'in navigator))return;window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(function(reg){if(reg.waiting)document.querySelector('#updateToast').hidden=false;reg.addEventListener('updatefound',function(){const worker=reg.installing;if(!worker)return;worker.addEventListener('statechange',function(){if(worker.state==='installed'&&navigator.serviceWorker.controller)document.querySelector('#updateToast').hidden=false})})}).catch(function(){const p=document.createElement('p');p.className='warning';p.textContent='离线功能暂时不可用，但在线计算仍可正常使用。';installHelp.appendChild(p)})});navigator.serviceWorker.addEventListener('controllerchange',function(){if(controllerReloaded)return;controllerReloaded=true;location.reload()})}

renderActivities();const saved=loadData();setValues(saved&&saved.profile?saved.profile:null);updateSteps();setupPlatformHelp();setupServiceWorker();
form.addEventListener('input',function(e){if(e.target.matches('input[type=range]'))syncOutputs();save()});form.addEventListener('change',save);
document.querySelectorAll('[data-change]').forEach(function(b){b.onclick=function(){const el=form.elements[b.dataset.change];el.value=Math.min(Number(el.max),Math.max(Number(el.min),Number(el.value)+Number(b.dataset.delta)));save()}});
document.querySelector('#next').onclick=function(){step=Math.min(5,step+1);updateSteps()};document.querySelector('#prev').onclick=function(){step=Math.max(1,step-1);updateSteps()};
document.querySelectorAll('[data-mode]').forEach(function(b){b.onclick=function(){document.querySelectorAll('[data-mode]').forEach(function(x){x.classList.remove('active')});b.classList.add('active');document.body.classList.toggle('all-mode',b.dataset.mode==='all');updateSteps()}});
form.onsubmit=function(e){e.preventDefault();if(submitting)return;submitting=true;const button=document.querySelector('#submit');button.disabled=true;try{const r=calculateNutrition(values());if(!r.ok){showErrors(r.errors);return}errorsEl.hidden=true;renderResult(r);save()}finally{window.setTimeout(function(){submitting=false;button.disabled=false},350)}};
document.querySelector('#calibration').onsubmit=function(e){e.preventDefault();if(!lastResult){document.querySelector('#calibrationResult').innerHTML='<p class="warning">⚠️ 请先完成上方计算。</p>';return}const fd=new FormData(e.target),x={startWeight:fd.get('startWeight'),endWeight:fd.get('endWeight'),days:fd.get('days'),averageCalories:fd.get('averageCalories'),originalTdee:lastResult.tdee},r=calibrateTdee(x);document.querySelector('#calibrationResult').innerHTML=r.ok?`<p class="notice">实测维持热量约 ${round(r.measured)} 千卡；平滑后的参考值为 <b>${round(r.adjusted)} 千卡</b>。本次只各取旧值和实测值的50%。</p>`:`<p class="warning">⚠️ ${r.error}</p>`};
document.querySelector('#reset').onclick=function(){if(confirm('恢复默认设置？已记录的填写内容会被替换。')){setValues(DEFAULTS);save();resultEl.hidden=true;step=1;updateSteps()}};
document.querySelector('#clear').onclick=function(){if(confirm('确定清除当前设备上的所有营养计算数据吗？此操作无法撤销。')){clearData();setValues(DEFAULTS);resultEl.hidden=true;alert('本机数据已清除。')}};
installBtn.onclick=function(){if(deferredPrompt&&typeof deferredPrompt.prompt==='function'){deferredPrompt.prompt();if(deferredPrompt.userChoice&&typeof deferredPrompt.userChoice.then==='function')deferredPrompt.userChoice.then(function(){deferredPrompt=null;installBtn.hidden=true})}else safeScroll(installHelp)};
document.querySelector('#reload').onclick=function(){if(!('serviceWorker'in navigator)){location.reload();return}navigator.serviceWorker.getRegistration().then(function(reg){if(reg&&reg.waiting)reg.waiting.postMessage('SKIP_WAITING');else location.reload()}).catch(function(){location.reload()})};
window.__nutritionAppReady=true;const runtimeError=document.querySelector('#runtimeError');if(runtimeError)runtimeError.hidden=true;
