import { CONFIG, DEFAULTS } from './config.js';
import { calculateNutrition, calibrateTdee, mealDistribution } from './calculator.js';
import { loadData, saveData, clearData } from './storage.js';

const form=document.querySelector('#calculator'), resultEl=document.querySelector('#result'), errorsEl=document.querySelector('#errors');
let step=1,lastResult=null,deferredPrompt=null;
const fields=['age','sex','height','weight','activity','goal','bodyFat','targetWeight','strength','cardio','duration','steps','workType','goalRate','pregnant','breastfeeding','kidney','liver','diabetes','eatingDisorder','medicalGuidance'];
function values(){const fd=new FormData(form),o={};for(const k of fields){const el=form.elements[k];o[k]=el?.type==='checkbox'?el.checked:(fd.get(k)??'')}return o}
function setValues(data){for(const [k,v] of Object.entries({...DEFAULTS,...data})){const el=form.elements[k];if(!el)continue;if(el instanceof RadioNodeList){const hit=[...el].find(x=>x.value===String(v));if(hit)hit.checked=true}else if(el.type==='checkbox')el.checked=Boolean(v);else el.value=v}syncOutputs()}
function syncOutputs(){document.querySelector('#heightOut').value=form.height.value;document.querySelector('#weightOut').value=form.weight.value}
function save(){if(!saveData({profile:values()}))showErrors(['浏览器未允许保存数据；仍可计算，但下次打开需要重新填写'])}
function renderActivities(){document.querySelector('#activityChoices').innerHTML=Object.entries(CONFIG.activity).map(([id,a])=>`<label><input type="radio" name="activity" value="${id}"><span><b>${a.title}</b><small>${a.example}</small></span></label>`).join('')}
function updateSteps(){document.querySelectorAll('.step').forEach(s=>s.hidden=document.body.classList.contains('all-mode')?false:Number(s.dataset.step)!==step);document.querySelector('#prev').hidden=step===1||document.body.classList.contains('all-mode');document.querySelector('#next').hidden=step===5||document.body.classList.contains('all-mode');document.querySelector('#submit').hidden=step!==5&&!document.body.classList.contains('all-mode');window.scrollTo({top:0,behavior:'smooth'})}
function showErrors(errors){errorsEl.innerHTML='<b>⚠️ 请修改以下内容：</b><ul>'+errors.map(x=>`<li>${x}</li>`).join('')+'</ul><p>特殊情况请咨询医生或营养师。</p>';errorsEl.hidden=false;errorsEl.scrollIntoView({behavior:'smooth',block:'center'})}
const round=n=>Math.round(n), pct=n=>Math.round(n*100);
function renderResult(r){lastResult=r;const m=r.macros;resultEl.innerHTML=`<div class="hero">您每天大约可以吃：<strong>${round(r.target)} 千卡</strong></div>${r.warnings.map(w=>`<p class="warning">${w}</p>`).join('')}<div class="macro-grid"><div class="macro">蛋白质<strong>${round(m.protein.grams)}克</strong><small>${round(m.protein.calories)}千卡 · ${pct(m.protein.share)}%</small></div><div class="macro">脂肪<strong>${round(m.fat.grams)}克</strong><small>${round(m.fat.calories)}千卡 · ${pct(m.fat.share)}%</small></div><div class="macro">碳水化合物<strong>${round(m.carbs.grams)}克</strong><small>${round(m.carbs.calories)}千卡 · ${pct(m.carbs.share)}%</small></div></div><div class="bar" aria-label="营养素热量比例"><span class="protein" style="width:${pct(m.protein.share)}%"></span><span class="fat" style="width:${pct(m.fat.share)}%"></span><span class="carbs" style="width:${pct(m.carbs.share)}%"></span></div><ul class="details-list"><li>基础代谢（BMR）：${round(r.bmr)} 千卡</li><li>维持体重所需热量（TDEE）：${round(r.tdee)} 千卡</li><li>维持热量参考范围：${round(r.tdeeRange[0])}～${round(r.tdeeRange[1])} 千卡</li><li>当前目标热量：${round(r.target)} 千卡</li><li>采用公式：${r.formula}</li><li>活动系数：${r.factor}</li><li>蛋白质计算依据：${r.referenceWeight.label} ${round(r.referenceWeight.value)} kg（${r.proteinRule.label}，${r.proteinRule.def}g/kg）</li></ul><p class="notice">实际维持热量会受到步数、训练强度、睡眠、肌肉量和个体差异影响，建议结合2至3周体重变化进行调整。</p><h3>分餐建议</h3><div class="mode"><button id="threeMeals" class="active">分成三餐</button><button id="fourMeals">分成四餐</button></div><div id="meals"></div>`;resultEl.hidden=false;renderMeals(3);resultEl.querySelector('#threeMeals').onclick=()=>renderMeals(3);resultEl.querySelector('#fourMeals').onclick=()=>renderMeals(4);resultEl.scrollIntoView({behavior:'smooth'});}
function renderMeals(count){const items=mealDistribution(lastResult,count);document.querySelector('#meals').innerHTML=items.map(x=>`<div class="meal"><b>${x.name} ${pct(x.ratio)}%</b>：约 ${round(x.calories)}千卡；蛋白质${round(x.protein)}克、脂肪${round(x.fat)}克、碳水${round(x.carbs)}克</div>`).join('');document.querySelector('#threeMeals').classList.toggle('active',count===3);document.querySelector('#fourMeals').classList.toggle('active',count===4)}

renderActivities();setValues(loadData()?.profile);updateSteps();
form.addEventListener('input',e=>{if(e.target.matches('input[type=range]'))syncOutputs();save()});form.addEventListener('change',save);
document.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>{const el=form.elements[b.dataset.change];el.value=Math.min(Number(el.max),Math.max(Number(el.min),Number(el.value)+Number(b.dataset.delta)));save()});
document.querySelector('#next').onclick=()=>{step=Math.min(5,step+1);updateSteps()};document.querySelector('#prev').onclick=()=>{step=Math.max(1,step-1);updateSteps()};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.body.classList.toggle('all-mode',b.dataset.mode==='all');updateSteps()});
form.onsubmit=e=>{e.preventDefault();const r=calculateNutrition(values());if(!r.ok)return showErrors(r.errors);errorsEl.hidden=true;renderResult(r);save()};
document.querySelector('#calibration').onsubmit=e=>{e.preventDefault();if(!lastResult){document.querySelector('#calibrationResult').innerHTML='<p class="warning">⚠️ 请先完成上方计算。</p>';return}const x=Object.fromEntries(new FormData(e.target));const r=calibrateTdee({...x,originalTdee:lastResult.tdee});document.querySelector('#calibrationResult').innerHTML=r.ok?`<p class="notice">实测维持热量约 ${round(r.measured)} 千卡；平滑后的参考值为 <b>${round(r.adjusted)} 千卡</b>。本次只各取旧值和实测值的50%。</p>`:`<p class="warning">⚠️ ${r.error}</p>`};
document.querySelector('#reset').onclick=()=>{if(confirm('恢复默认设置？已记录的填写内容会被替换。')){setValues(DEFAULTS);save();resultEl.hidden=true;step=1;updateSteps()}};
document.querySelector('#clear').onclick=()=>{if(confirm('确定清除当前设备上的所有营养计算数据吗？此操作无法撤销。')){clearData();setValues(DEFAULTS);resultEl.hidden=true;alert('本机数据已清除。')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.querySelector('#installBtn').hidden=false});document.querySelector('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else document.querySelector('#installHelp').scrollIntoView({behavior:'smooth'})};
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(reg=>{reg.addEventListener('updatefound',()=>{const w=reg.installing;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)document.querySelector('#updateToast').hidden=false})})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}
document.querySelector('#reload').onclick=async()=>{const reg=await navigator.serviceWorker.getRegistration();reg?.waiting?.postMessage('SKIP_WAITING')};
