const VERSION='family-wellness-pwa-7c4e91-ios-v2.0.0';
const CACHE=`${VERSION}-app`;
const CACHE_PREFIX='family-wellness-pwa-7c4e91-';
const CORE_ASSETS=['./','./index.html','./styles.css','./manifest.webmanifest','./js/config.js','./js/calculator.js','./js/storage.js','./js/app.js','./icons/icon-192.png','./icons/icon-512.png'];

function cacheResponse(request,response){if(!response||!response.ok)return Promise.resolve();return caches.open(CACHE).then(function(cache){return cache.put(request,response.clone())}).catch(function(){return undefined})}
function currentCacheMatch(request){return caches.open(CACHE).then(function(cache){return cache.match(request)}).catch(function(){return undefined})}
function cleanLegacyEntries(){return caches.open('nutrition-v1.0.1-app').then(function(cache){return cache.keys().then(function(requests){return Promise.all(requests.filter(function(request){return new URL(request.url).pathname.indexOf('/family-wellness-pwa-7c4e91/')===0}).map(function(request){return cache.delete(request)}))})}).catch(function(){return undefined})}
function offlinePage(){return new Response('<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>暂时无法打开</title><main style="font:18px system-ui;padding:24px"><h1>暂时无法打开</h1><p>请检查网络后重新加载。打开过的网站会在缓存恢复后继续可用。</p><button onclick="location.reload()" style="font:inherit;min-height:48px">重新加载</button></main>',{headers:{'Content-Type':'text/html; charset=utf-8'}})}

self.addEventListener('install',function(event){event.waitUntil(caches.open(CACHE).then(function(cache){return Promise.all(CORE_ASSETS.map(function(url){return Promise.resolve().then(function(){return cache.add(url)}).catch(function(){return undefined})}))}))});
self.addEventListener('activate',function(event){event.waitUntil(caches.keys().then(function(keys){return Promise.all(keys.filter(function(key){return key.indexOf(CACHE_PREFIX)===0&&key!==CACHE}).map(function(key){return caches.delete(key)}))}).then(cleanLegacyEntries).then(function(){return self.clients.claim()}))});
self.addEventListener('fetch',function(event){const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith(fetch(request).then(function(response){cacheResponse('./index.html',response);return response}).catch(function(){return currentCacheMatch(request).then(function(cached){if(cached)return cached;return currentCacheMatch('./index.html')}).then(function(cached){if(cached)return cached;return currentCacheMatch('./')}).then(function(cached){return cached||offlinePage()})}));return}event.respondWith(currentCacheMatch(request).then(function(cached){if(cached)return cached;return fetch(request).then(function(response){cacheResponse(request,response);return response})}))});
self.addEventListener('message',function(event){if(event.data==='SKIP_WAITING')self.skipWaiting()});
